### ISSUE TITLE
Splash damage from monsters

### ISSUE THREAD

**Issue by viciious** [team-eternity/calico-doom#7]
Hi!

I'm working on a sister project D32X: Resurrection: https://github.com/viciious/d32xr and I've noticed that monster projectiles deal no damage to the player. Since we're sharing the same lineage I figured it might a good idea to ask you whether you've encountered similar issue in Calico.

Looking at info.c none of the monster projectiles have an explosion state as opposed to, say, rockets. This applies to both Calico and jaguardoom.

Thanks for your efforts and good luck with your project!

**Comment by AXDOOMER** [comment]
I tested Calico's v2.0 release and projectiles from Imps and Shotgun Zombies deal damage to the player. 

One thing that I noticed though is that the blast damage from rockets and barrels is reduced, or the blast's range is reduced. I don't know if that's a "feature" of the Jaguar version or if it's a bug.

**Comment by viciious** [comment]
It appears that in Calico all instances of 'extradata' have been replaced with 'extramobj' for latecalls, and that works.

One thing I did notice is that L_CrossSpecial still references 'extradata' here: https://github.com/team-eternity/calico-doom/blob/master/src/p_enemy.c#L780 , but it's never set to anything anywhere else in the code.
