### ISSUE TITLE
Level select is broken in the menu when game has never been played

### ISSUE THREAD

**Issue by AXDOOMER** [team-eternity/calico-doom#8]
When the game has never been played, the level select ("area") will be 0, which will try to load `MAP00` and crash with an error about `P_SetupLevel` unable to find `MAP00`. Decreasing the "area" lower than 0 will also cause a crash, but it cannot be increased. 

The bug is not present when levels have been completed because the "area" will be 1. 

I'm running this in Wine. I was able to get around this and playtest by editing the map numbers in the ROM to start from 0.

**Comment by haleyjd** [comment]
This is actually a bug in the config utility which I've already fixed (and am about to upload a fix for in the windows binary release). If you allow the game to generate the eeprom.cal file first, this shouldn't occur.
